### ISSUE TITLE
maven compile error

### ISSUE THREAD

**Issue by iokk3732** [Canner/wren-engine#1016] opened 2024-12-27 07:17 UTC
Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory

**Comment by goldmedal** [comment] 2024-12-27 07:21
I'm not sure what you mean. Could you provide the steps for reproducing or any log?

**Comment by goldmedal** [comment] 2024-12-27 07:26
By the way, the following steps work for my local environment.
1. `git clone https://github.com/Canner/wren-engine.git`
2. `cd wren-engine`
3. `./mvnw clean install -DskipTests`

**Comment by iokk3732** [comment] 2024-12-27 10:58
> By the way, the following steps work for my local environment.
> 
> 1. `git clone https://github.com/Canner/wren-engine.git`
> 2. `cd wren-engine`
> 3. `./mvnw clean install -DskipTests`

Thank you! It has worked now. Previously, I downloaded the source code directly, but now I used git clone, and the compilation has passed. However, in the trino-parser module, there's currently an error: "Cannot resolve symbol 'TypeCalculationParser'".
![image](https://github.com/user-attachments/assets/42890c74-53af-40b1-8ac8-c01307d9a3a7)

**Comment by iokk3732** [comment] 2024-12-27 11:13
I want to directly debug the project, but when I run wren-server, I encounter configuration file errors. What configurations need to be added to config.properties, and where should this file be placed?

**Comment by goldmedal** [comment] 2024-12-27 11:40
> Thank you! It has worked now. Previously, I downloaded the source code directly, but now I used git clone, and the compilation has passed. However, in the trino-parser module, there's currently an error: "Cannot resolve symbol 'TypeCalculationParser'". ![image](https://private-user-images.githubusercontent.com/141700052/398922005-42890c74-53af-40b1-8ac8-c01307d9a3a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTkzNzYsIm5iZiI6MTczNTI5OTA3NiwicGF0aCI6Ii8xNDE3MDAwNTIvMzk4OTIyMDA1LTQyODkwYzc0LTUzYWYtNDBiMS04YWM4LWMwMTMwN2Q5YTNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxMTMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjQzMjQwNTdhNjhmODgzZWYwODJjZDNiNmFkNzlmNDg1MzQyZWY1MzM4OTk3YjViYjMzNmQ2Yjk4ZmI2MDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vuXaBgxcWx0Rz7_1p3fGET866OyoNVayABhIlS8retc)
>

It seems that you use the IntelliJ as the IDE. I think you can run the maven build through IDE directly. (IDE will link them automatically).
```
mvn clean install -DskipTests
```
Because some classes of Wren Server are generated by other tools (e.g. anltr4), you need to generate them first.

> I want to directly debug the project, but when I run wren-server, I encounter configuration file errors. What configurations need to be added to config.properties, and where should this file be placed?
>

You need to add the VM options when starting the server. You can put the config on where you want. Just add the path to this option.
```
-Dconfig=etc.local/config.properties
```

I provided a minimized `config.properties` here.
```
node.environment=test
wren.experimental-enable-dynamic-fields=true
```
Because most config of wren engine has been deprecated, I believe you can just use the above config to start the Wren Server.
For more additional configs, you can find them on the classes named `xxxConfig` or `ConfigManager`.

hope helpful.

**Comment by iokk3732** [comment] 2024-12-27 12:35
Yes, I am using IntelliJ as my IDE. Currently, I have configured the startup parameters in IntelliJ as follows:

io.wren.server.WrenServer -Dconfig=/Users/jianchuanli/mindflow/opensource/wren-engine/config.properties

However, after running it, I am still encountering the following error:

==========

Errors:

Invalid configuration property node.environment: must not be null (for class io.airlift.node.NodeConfig.environment)
==========


![image](https://github.com/user-attachments/assets/d136e6ea-4bfd-48b3-aeb2-94475011a31c)
![image](https://github.com/user-attachments/assets/9ebfe1a4-7b12-43f6-bbb0-60251f83a41b)
![image](https://github.com/user-attachments/assets/305a6fa8-9414-483a-bb03-120ed06fd9af)

**Comment by goldmedal** [comment] 2024-12-27 12:47
I think you put the config at the wrong place. Where you set is the **program argument** but it should be set at VM options.
You can find the `VM option` by clicking `Modify options`. Then, you will get an additional field for `VM option`
<img width="555" alt="Screenshot 2024-12-27 at 8 44 55 PM" src="https://github.com/user-attachments/assets/14cc10e0-d41f-4c7b-9809-ff20fcfd7911" />

**Comment by iokk3732** [comment] 2024-12-29 11:31
<img width="1249" alt="截屏2024-12-29 19 28 49" src="https://github.com/user-attachments/assets/4ac4b88f-a75f-4aba-9105-71429080ed2b" />
The log that appears indicates success, right?

**Comment by goldmedal** [comment] 2024-12-29 13:03
> <img alt="截屏2024-12-29 19 28 49" width="1249" src="https://private-user-images.githubusercontent.com/141700052/399156398-4ac4b88f-a75f-4aba-9105-71429080ed2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Nzc2NzYsIm5iZiI6MTczNTQ3NzM3NiwicGF0aCI6Ii8xNDE3MDAwNTIvMzk5MTU2Mzk4LTRhYzRiODhmLWE3NWYtNGFiYS05MTA1LTcxNDI5MDgwZWQyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOVQxMzAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmE1ODY3OWY5Y2NmOTZjNmFlYmJjYWQ2ZWMyOTc0ZWQ4YmM4YTk3NjRkMjQ4NDk1YWNiZTI5ODY1NmU3N2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.knvS0TKZGu7Kk9rUR_3VT5mXQPv3tPAM7dj01voWmqs"> The log that appears indicates success, right?

Exactly

**Comment by iokk3732** [comment] 2024-12-30 02:11
Thanks very much.     😊😊😊😊😊

**Comment by goldmedal** [comment] 2024-12-30 02:30
It seems this issue has been resolved. I want to close it. If you have other questions, feel free to raise another issue. Thanks

**Closed by goldmedal** 2024-12-30 02:30 UTC
Labels: bug
